"""auto

Revision ID: 456d4ab2998a
Revises: c8cf5eaec4a9
Create Date: 2020-08-16 14:49:40.080668+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456d4ab2998a'
down_revision = 'c8cf5eaec4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_account_user_id'), 'user_account', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_user_id'), table_name='user_account')
    # ### end Alembic commands ###
