"""auto

Revision ID: c8cf5eaec4a9
Revises: 0f68be1d9965
Create Date: 2020-08-16 10:12:42.878714+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c8cf5eaec4a9'
down_revision = '0f68be1d9965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transaction', ['id'])
    op.create_unique_constraint(None, 'user_account', ['id'])
    op.create_unique_constraint(None, 'user_bank_account', ['id'])
    op.create_unique_constraint(None, 'user_wallet', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_wallet', type_='unique')
    op.drop_constraint(None, 'user_bank_account', type_='unique')
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_constraint(None, 'transaction', type_='unique')
    # ### end Alembic commands ###
