"""auto

Revision ID: 0f68be1d9965
Revises: 
Create Date: 2020-08-16 10:12:36.251672+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '0f68be1d9965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kind', postgresql.ENUM('DEPOSIT', 'SEND', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'HOLD', 'COMMITTED', 'REJECTED', 'CANCELLED', 'ERROR', name='transactionstatus'), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_bank_account',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_wallet',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_wallet')
    op.drop_table('user_bank_account')
    op.drop_table('transaction')
    op.drop_table('user_account')
    # ### end Alembic commands ###
